### ISSUE TITLE
Shouldn't login cookies be saving despite a refresh?

### ISSUE THREAD

**Issue by adamkhan** [nuxt-community/strapi-module#98]
To log in to my site I've moved from an auth recipe to using this Nuxt Strapi module. After a refresh the cookie is still there but I am effectively logged out and get the following 2 console messages:

> Cookie “strapi_jwt” has been rejected because it is already expired.
> 
> Cookie “strapi_jwt” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Now with v0.3 I've made some changes to the cookie setting:
expires: 365d
sameSite: Lax 
secure: true
httOnly: false

But nothing helps... 

I notice that localStorage gets an item with a key of strapi_jwt. Its value contains "token" as a long hash, then "expires" as a date that looks like the moment of logging in and therefore already in the past. Is it this localStorage item that is effectively logging me out?

Anybody got any idea what I'm missing here?

**Comment by adamkhan** [comment]
Hi @Atinux,

Thanks for pointing me in what looks like the right direction. In my installation I inserted console.logs to the functions you point out in the file /node_modues/@nuxtjs/strapi/lib/runtime as follows:

`getToken() {
        let token;
        const clientStorage = this.getClientStorage();
        console.log("getToken: clientStorage");
        console.log(clientStorage);
        if (clientStorage) {
            const session = destr(clientStorage.getItem(this.options.key));
            if (session && !isExpired(session.expires)) {
                token = session.token;
            }
        }
        if (!token) {
            token = this.$cookies.get(this.options.key);
        }
        return token;
    }
    setToken(token) {
        const expires = this.options.expires === 'session' ? undefined : getExpirationDate(this.options.expires);
        console.log("expires");
        console.log(expires);
        const clientStorage = this.getClientStorage();
        clientStorage && clientStorage.setItem(this.options.key, JSON.stringify({ token, expires }));
        console.log("setToken: clientStorage");
        console.log(clientStorage);
        this.$cookies.set(this.options.key, token, {
            ...this.options.cookie,
            expires
        });
        this.$http.setToken(token, 'Bearer');
    }`

And in my console I get the following (also attached screenshot for clarity):

<img width="720" alt="Screen Shot 2021-01-21 at 12 22 03 PM" src="https://user-images.githubusercontent.com/776967/105351287-46987600-5be4-11eb-8aaf-d73812b1cfee.png">


`
Cookie “strapi_jwt” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite quick
Cookie “strapi_jwt” has been rejected because it is already expired. quick
Nuxt SSR client.js:50
getToken: clientStorage client.js:51
null client.js:51
expires client.js:51
2022-01-21T12:17:49.088Z client.js:51
setToken: clientStorage client.js:51
null client.js:51
getToken: clientStorage client.js:51
null client.js:51
expires client.js:51
2022-01-21T12:17:49.897Z client.js:51
setToken: clientStorage client.js:51
null client.js:51
getToken: clientStorage strapi.js:138
Storage { filterClosedRackmounts: "false", strapi_jwt: "{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYzMyYTFjYTJiNDMxYTU5M2IxNzNhYSIsImlhdCI6MTYxMTIzMTIyNSwiZXhwIjoxNjQyNzY3MjI1fQ.yYGuHFvFTHVqNV6jq0pNzCUy3VftoLOgKS8iQoilI0I\",\"expires\":\"2022-01-21T12:16:20.458Z\"}", navigatingRacks: "false", alphabetizeRackmounts: "false", length: 4 }
strapi.js:139
expires strapi.js:153
Date Fri Jan 21 2022 12:17:56 GMT+0000 (Greenwich Mean Time)
strapi.js:154
setToken: clientStorage strapi.js:157
Storage { filterClosedRackmounts: "false", strapi_jwt: "{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViYzMyYTFjYTJiNDMxYTU5M2IxNzNhYSIsImlhdCI6MTYxMTIzMTIyNSwiZXhwIjoxNjQyNzY3MjI1fQ.yYGuHFvFTHVqNV6jq0pNzCUy3VftoLOgKS8iQoilI0I\",\"expires\":\"2022-01-21T12:17:56.036Z\"}", navigatingRacks: "false", alphabetizeRackmounts: "false", length: 4 }
strapi.js:158
[HMR] connected client.js:95
You are running Vue in development mode.
`

So it appears that first Nuxt SSR does not see clientStorage and the expiration date is in the immediate past, but then the browser does see the stored token client-side once it's too late? (I don't really understand how the tokens work...)

If that is indeed the problem, how to get SSR to see the token? I thought setting httpOnly to false might have solved that...

**Comment by kgnfth** [comment]
my cookie is never set its always empty

**Comment by kgnfth** [comment]
i have the same issue
i have set it like this

```
  expires: '365d',
  secure: true,
  httpOnly: false,
```
i get a coockie like this 
![image](https://user-images.githubusercontent.com/73314940/110160231-07b52d00-7dec-11eb-84ba-136e625de72d.png)

but after refreshing im redirected to login page but the cookie is still there
so i added a back button to my login and i can still browse my site without logging in
my strapi api is set to authentication only.. so this means i am still logged in but i keep getting redirected to auth page after page refresh

**Comment by aysnet1** [comment]
**i resolved that issue by setting the path value of cookies** 
set path cookies to '/'
like this :
```
 strapi: {
    cookie: {
      path: '/', 
   // other option...
    }
```

**Comment by adamkhan** [comment]
Doesn't help me. I have:

```
strapi: {
		// url: '/api/strapi',
		url: process.env.strapiHost + process.env.strapiPort,
		entities: ['feeds', 'users'],
	    expires: '365d',
	    // key: 'userJwt',
	    cookie: {
		    expires: 7 * 24 * 3600 * 1000, // '365d',
	    	sameSite: 'lax',
	    	secure: true, // seems to block cookie being created even
	    	path: '/',
	    	httpOnly: false, // can't do this as i think we are both client- & server-side
	    }
	    // entities: ['']
	},
```

**Comment by benjamincanac** [comment]
Indeed, this happens because the cookie is set on the redirect page (ex: `/auth/github/callback`) since the app is loaded from there. On logout, the removed cookie is from the path `/`.

Like @aysnet1 said, forcing the path to `/` should solve this issue:

```js
strapi: {
  cookie: {
    path: '/'
  }
}
```

**Comment by adamkhan** [comment]
Setting path to '/' does not help. Still stuck here...

**Comment by aysnet1** [comment]
> Setting path to '/' does not help. Still stuck here...

You should delete all cookies from your site, and if that doesn't solve the problem, then trying to put the login file in the page folder 📂 url/login and see what happens?

**Comment by adamkhan** [comment]
Hi @aysnet1, thanks for responding. I'm embarrassed to say how many times I have cleared cookies from the site!

Can you explain what is special about the /url/login path? I haven't seen anything that would indicate that the page where I'm logging in from should make any difference.

**Comment by adamkhan** [comment]
Well, curiouser and curiouser: I have another, less developed Strapi/Nuxt combination also on localhost (Nuxt v2.15.4 latest, Strapi v3.4.0) — call it Site B — and here the @nuxtjs/strapi login works just fine. However, when I refresh the first site, and then refresh this Site B, the user on Site B gets logged out. When I refresh Site B again, the user gets logged back in.

Something on my original site is so messed up that it's even affecting other localhost sites. The warnings I get are:

#Cookie “strapi_jwt” has been rejected because it is already expired.
Cookie “strapi_jwt” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by adamkhan** [comment]
Well I have found the culprit. In the unlikely event anyone else creates this problem for themselves, here it is:

After reading (without truly understanding) https://www.sumcumo.com/en/global-state-mutations-in-ssr-with-vue-and-node-js I tried to improve performance by sticking the following in nuxt.config.sys

```
render: {
	bundleRenderer: {
		runInNewContext: false,
	},
},
```

Oops.

**Comment by adhamfarrag** [comment]
I still have the same issue, tried relying on cookies instead of `$strapi.user` for user/guest middleware and saving strapi user content from Store, on page refresh I don't logout but all content coming from Store is null. It only happens in production mode so I can't debug and see if it somehow lose access to Store or what's the reason.

This is my configuration


```js
  strapi: {
    url: '/api',
    entities: [
      { name: 'organizations' },
      { name: 'sections' },
      { name: 'articles' },
      { name: 'users' },
    ],
    key: 'authToken',
    expires: '31d',
    cookie: {
      expires: 7 * 24 * 3600 * 1000,
      sameSite: true,
      secure: true,
      path: '/',
      httpOnly: false,
    },
  },

  render: {
    bundleRenderer: {
      runInNewContext: false,
    },
  },
```

@adamkhan Thanks for your efforts across several issues here. Do you still have any problems related to this issue ?

**Comment by adamkhan** [comment]
Hi @adhamfarrag,

I should have posted here when I fixed it. Turns out I only had the problem in prod not dev mode (the server didn't matter).

The approach that eventually worked was to remove every component on my app bit by bit until it worked. For me the culprit was Fontawesome, something seemingly totally unrelated but I can't remember why. I think I may have set up Fontawesome with http- rather than https-based URLs which the Strapi Nuxt module didn't like.
